inverted.exe : main.o check_operation.o create_database.o display_database.o save_database.o search_database.o update_database.o
	gcc -o inverted.exe main.o check_operation.o create_database.o display_database.o save_database.o search_database.o update_database.o
main.o : main.c
	gcc -c main.c
check_operation.o : check_operation.c
	gcc -c check_operation.c
create_database.o : create_database.c
	gcc -c create_database.c
display_database.o : display_database.c
	gcc -c display_database.c
save_database.o : save_database.c
	gcc -c save_database.c
search_database.o : search_database.c
	gcc -c search_database.c					
update_database.o : update_database.c
	gcc -c update_database.c	